version: "2"

services:
  user-service:
    build: spring-boot/spring-boot-user
    environment:
      SPRING_PROFILES_ACTIVE: microservice
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/waber_user
      SPRING_RABBITMQ_HOST: rabbitmq
      OTEL_TRACES_EXPORTER: otlp_span
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: http://tempo:55680
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: "true"
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/api/users`) || PathPrefix(`/api/passengers`) || PathPrefix(`/api/drivers`)"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.routers.user-service.service=user-service"
      - "traefik.http.services.user-service.loadbalancer.server.port=80"
      - "traefik.http.routers.user-service.priority=1"
#    logging:
#      driver: loki
#      options:
#        loki-url: 'http://localhost:3100/api/prom/push'

  match-service:
    build: spring-boot/spring-boot-match
    environment:
      SPRING_PROFILES_ACTIVE: microservice
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/waber_match
      SPRING_RABBITMQ_HOST: rabbitmq
      OTEL_TRACES_EXPORTER: otlp_span
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: http://tempo:55680
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: "true"
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.match-service.rule=PathPrefix(`/api/users/{passengerId:[0-9]+}/matches`) || PathPrefix(`/api/matches`)"
      - "traefik.http.routers.match-service.entrypoints=web"
      - "traefik.http.routers.match-service.service=match-service"
      - "traefik.http.services.match-service.loadbalancer.server.port=80"
      - "traefik.http.routers.match-service.priority=2"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  trip-service:
    build: spring-boot/spring-boot-trip
    environment:
      SPRING_PROFILES_ACTIVE: microservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/waber_trip
      SPRING_RABBITMQ_HOST: rabbitmq
      OTEL_TRACES_EXPORTER: otlp_span
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: http://tempo:55680
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: "true"
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trip-service.rule=PathPrefix(`/api/trips`) || PathPrefix(`/api/users/{passengerId:[0-9]+}/trips`)"
      - "traefik.http.routers.trip-service.entrypoints=web"
      - "traefik.http.routers.trip-service.service=trip-service"
      - "traefik.http.services.trip-service.loadbalancer.server.port=80"
      - "traefik.http.routers.trip-service.priority=3"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  payment-service:
    build: spring-boot/spring-boot-payment
    environment:
      SPRING_PROFILES_ACTIVE: microservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/waber_payment
      SPRING_RABBITMQ_HOST: rabbitmq
      OTEL_TRACES_EXPORTER: otlp_span
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: http://tempo:55680
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: "true"
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-service.rule=PathPrefix(`/api/payments`)"
      - "traefik.http.routers.payment-service.entrypoints=web"
      - "traefik.http.routers.payment-service.service=payment-service"
      - "traefik.http.services.payment-service.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  broker:
    build: spring-boot/spring-boot-broker
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      OTEL_TRACES_EXPORTER: otlp_span
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: http://tempo:55680
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: "true"
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broker.rule=PathPrefix(`/broker`) || PathPrefix(`/topic`)"
      - "traefik.http.routers.broker.entrypoints=web"
      - "traefik.http.routers.broker.service=broker"
      - "traefik.http.services.broker.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'


networks:
  default:
    external:
      name: ddd-benchmark-waber_default

